[build]
buildCommand = "npm run build"

[deploy]
preDeployCommand = ["npm run db:prepare:prod"]
startCommand = "npm run ${RAILWAY_START_SCRIPT}"
numReplicas = 1
healthcheckPath = "/healthz"
healthcheckTimeout = 30
restartPolicyType = "ALWAYS"
overlapSeconds = 0
drainingSeconds = 30
